"""
Brand glyph generator (DESIGN.md section 9, task DT3).

Traces the "P" of the bundled JetBrains Mono Medium (app/src/main/res/font/jetbrains_mono_medium.ttf)
with fontTools and writes the three vector drawables that carry it:

  app/src/main/res/drawable/ic_launcher_foreground.xml   108 viewport, Ink glyph, Accent tick
  app/src/main/res/drawable/ic_launcher_monochrome.xml   same paths, one color, for themed icons
  app/src/main/res/drawable/ic_stat_plainticker.xml      24 viewport, white, notification small icon

Layout: the glyph's cap height is CAP of the viewport, the tick (the gauge tick, 2 high in the
launcher) sits GAP below the baseline and spans the glyph's ink width; the whole block is centered.
In the 108 launcher viewport the block stays inside the 66 safe-zone circle (the script asserts it).
Only absolute path commands are emitted, so BrandAssetsTest can walk the coordinates.

Run from anywhere:  PYTHONIOENCODING=utf-8 python design/brand/glyph.py
Needs:              python -m pip install fonttools
"""
import math
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONT = ROOT / "app/src/main/res/font/jetbrains_mono_medium.ttf"
DRAWABLE = ROOT / "app/src/main/res/drawable"

INK = "#E8ECF1"
ACCENT = "#5AA9E6"
WHITE = "#FFFFFF"


def number(value, decimals=2):
    rounded = round(value, decimals)
    return str(int(rounded)) if rounded == int(rounded) else repr(rounded)


def trace(viewport, cap, gap, tick):
    """Returns (glyph_path, tick_path, block) for the given viewport, all coordinates absolute."""
    font = TTFont(str(FONT))
    glyph_set = font.getGlyphSet()
    glyph = glyph_set[font.getBestCmap()[ord("P")]]
    bounds = BoundsPen(glyph_set)
    glyph.draw(bounds)
    x_min, y_min, x_max, y_max = bounds.bounds
    # The layout maps font y=0 to the baseline and y_max to the cap line, so the glyph must sit on
    # the baseline with no overshoot below it (true for the flat-footed P; a swap of glyph or font
    # fails here instead of drifting).
    assert y_min == 0, f"glyph bottom is {y_min}, not on the baseline"

    scale = cap / y_max
    width = (x_max - x_min) * scale
    block_height = cap + gap + tick
    top = viewport / 2 - block_height / 2
    baseline = top + cap
    left = viewport / 2 - width / 2

    pen = SVGPathPen(glyph_set, ntos=number)
    # Font y points up, the viewport y points down: flip around the baseline.
    glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, left - x_min * scale, baseline)))
    glyph_path = pen.getCommands()

    tick_top = baseline + gap
    tick_path = "M{} {}H{}V{}H{}Z".format(
        number(left), number(tick_top), number(left + width), number(tick_top + tick), number(left)
    )
    block = (left, top, left + width, tick_top + tick)
    return glyph_path, tick_path, block


def vector(size, glyph_path, glyph_color, tick_path, tick_color, comment):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!--\n{comment}\n  Generated by design/brand/glyph.py, do not edit by hand.\n-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size}dp"\n'
        f'    android:height="{size}dp"\n'
        f'    android:viewportWidth="{size}"\n'
        f'    android:viewportHeight="{size}">\n'
        "    <path\n"
        f'        android:fillColor="{glyph_color}"\n'
        f'        android:pathData="{glyph_path}" />\n'
        "    <path\n"
        f'        android:fillColor="{tick_color}"\n'
        f'        android:pathData="{tick_path}" />\n'
        "</vector>\n"
    )


def main():
    glyph, tick, block = trace(viewport=108, cap=40, gap=5, tick=2)
    center = 54
    radius = max(math.hypot(x - center, y - center) for x in (block[0], block[2]) for y in (block[1], block[3]))
    assert radius <= 33, f"launcher glyph leaves the 66 safe zone: corner radius {radius:.2f}"
    where = "  Block {} to {} across, {} to {} down, corner radius {:.1f} of the 33 safe zone.".format(
        number(block[0]), number(block[2]), number(block[1]), number(block[3]), radius
    )
    launcher = (
        "  Brand glyph, DESIGN.md section 9: JetBrains Mono Medium P (the bundled\n"
        "  res/font/jetbrains_mono_medium.ttf, v2.304) in Ink, cap height 40 of the 108 adaptive icon\n"
        "  viewport, with the gauge tick, 2 high in Accent, 5 below the baseline.\n" + where
    )
    (DRAWABLE / "ic_launcher_foreground.xml").write_text(vector(108, glyph, INK, tick, ACCENT, launcher), newline="\n")

    mono = (
        "  Monochrome layer of the adaptive icon (themed icons, Android 13 and later): the launcher\n"
        "  glyph and tick as one shape, the launcher supplies the color."
    )
    (DRAWABLE / "ic_launcher_monochrome.xml").write_text(vector(108, glyph, WHITE, tick, WHITE, mono), newline="\n")

    glyph24, tick24, block24 = trace(viewport=24, cap=14, gap=2, tick=1.5)
    # A 24 status bar icon keeps 2 of padding on every side (the 20 live area).
    assert all(2 <= v <= 22 for v in block24), f"notification glyph leaves the 20 live area: {block24}"
    stat = (
        "  Notification small icon: the brand glyph in white on transparent, the system tints it.\n"
        "  Cap height 14 of the 24 viewport, tick 1.5 high, 2 below the baseline."
    )
    (DRAWABLE / "ic_stat_plainticker.xml").write_text(vector(24, glyph24, WHITE, tick24, WHITE, stat), newline="\n")
    print("wrote ic_launcher_foreground.xml, ic_launcher_monochrome.xml, ic_stat_plainticker.xml")
    print(where.strip())


if __name__ == "__main__":
    main()
